Added support for Ubuntu 18 04
S2E/build-scripts pull request #22
Opened 2018-07-24 04:41 UTC by adrianherrera

2018-07-24 06:07 UTC, vitalych commented on determine_clang_binary_suffix.py
> +# Licensed under the GPL: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
Could you add the license header to the beginning and swich to MIT?

2018-07-24 06:07 UTC, vitalych commented on determine_clang_binary_suffix.py
> +    if major_version == 14 and minor_version >= 4:
I suppose we don't need to check this if we drop support for 14.

2018-07-24 06:10 UTC, vitalych commented
Did you check that the demo docker image builds and runs? I promise I'll work on Jenkins when I return from vacation :)

2018-07-24 06:11 UTC, vitalych requested changes
Looks great, few comments to address.

2018-07-25 02:03 UTC, adrianherrera commented
Actually no, the Docker containers don't work. Having the additional Python script throws a spanner in the works. I don't really want to pollute the `$(S2E_DIR)/source/s2e` directory with more symlinks (in fact I would argue that `Makefile.docker`, `Dockerfile`, `Dockerfile.dist`, etc. shouldn't be there anyway), so I'm trying to refactor a bit.

Hopefully I'll have a elegant solution soon. Maybe even before you finish your vacation :)

2018-07-25 21:31 UTC, adrianherrera commented
Okay, Docker demo is working fine.

All PRs are good to go 🚀

2018-07-26 06:05 UTC, vitalych approved these changes

2018-07-26 15:18 UTC, merged